name: Rust crate version pipeline

on: [push, pull_request]

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest

    env:
      working-directory: antikithera

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt
      - run: cd fast-geoip-rs && cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    env:
      working-directory: antikithera

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: clippy
          toolchain: stable
          override: true
      - run: cd fast-geoip-rs && cargo clippy -- -D warnings
